tag_host: http://localhost:8086
search_host: http://localhost:8085
fabric_url: https://host-76-74-28-229.contentfabric.io/config?self&qspace=main

tag_args: {"features": {"shot":{}, "asr": {"stream": "audio_1"}}}

min_content: 180

external_tags: rugbyviz.json