tag_host: http://localhost:8086
search_host: https://ai-02.contentfabric.io/search
fabric_url: https://host-154-14-192-69.contentfabric.io/config?self&qspace=main
live2vod_host: https://host-76-74-29-7.contentfabric.io

tag_args: {"features": {"shot":{}, "asr": {"stream": "audio_2"}, "french_asr": {"stream": "audio_2"}, "logo": {"model": {"fps":1}}, "ocr": {"model": {"fps":1}}}}

min_tag: 300
min_l2v: 300

external_tags: rugbyviz.json